=== k1000nary/simulator/src/EUREKA/G6KBundle/Resources/doc/DataSources.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DataSources">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DataSource" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="0">
							<xs:element name="Description" type="xs:string" minOccurs="0"/>
							<xs:element name="Namespace" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="prefix" type="xs:string"/>
									<xs:attribute name="uri" type="xs:anyURI"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Table" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Description" type="xs:string" minOccurs="0"/>
										<xs:element name="Column" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Description" type="xs:string" minOccurs="0"/>
													<xs:element name="Choices" minOccurs="0">
														<xs:complexType>
															<xs:choice>
																<xs:element name="Choice" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:string" use="required"/>
																		<xs:attribute name="value" type="xs:string" use="required"/>
																		<xs:attribute name="label" type="xs:string" use="required"/>
																	</xs:complexType>
																</xs:element>
																<xs:element name="Source">
																	<xs:complexType>
																		<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
																		<xs:attribute name="datasource" type="xs:string" use="required"/>
																		<xs:attribute name="returnType" use="required">
																			<xs:simpleType>
																				<xs:restriction base="xs:NMTOKEN">
																					<xs:enumeration value="json"/>
																					<xs:enumeration value="xml"/>
																					<xs:enumeration value="assocArray"/>
																					<xs:enumeration value="csv"/>
																				</xs:restriction>
																			</xs:simpleType>
																		</xs:attribute>
																		<xs:attribute name="request" type="xs:string"/>
																		<xs:attribute name="valueColumn" type="xs:string" use="required"/>
																		<xs:attribute name="labelColumn" type="xs:string" use="required"/>
																		<xs:attribute name="returnPath" type="xs:string"/>
																		<xs:attribute name="separator" type="xs:string"/>
																		<xs:attribute name="delimiter" type="xs:string"/>
																	</xs:complexType>
																</xs:element>
															</xs:choice>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute name="type" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:NMTOKENS">
															<xs:enumeration value="day"/>
															<xs:enumeration value="month"/>
															<xs:enumeration value="year"/>
															<xs:enumeration value="boolean"/>
															<xs:enumeration value="choice"/>
															<xs:enumeration value="date"/>
															<xs:enumeration value="money"/>
															<xs:enumeration value="integer"/>
															<xs:enumeration value="percent"/>
															<xs:enumeration value="number"/>
															<xs:enumeration value="text"/>
															<xs:enumeration value="textarea"/>
															<xs:enumeration value="country"/>
															<xs:enumeration value="region"/>
															<xs:enumeration value="department"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="label" type="xs:string"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
									<xs:attribute name="name" use="required"/>
									<xs:attribute name="label"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
						<xs:attribute name="name" use="required"/>
						<xs:attribute name="type" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="uri"/>
									<xs:enumeration value="database"/>
									<xs:enumeration value="internal"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="uri" type="xs:string"/>
						<xs:attribute name="method" default="GET">
							<xs:simpleType>
								<xs:restriction base="xs:NMTOKEN">
									<xs:enumeration value="GET"/>
									<xs:enumeration value="POST"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="database" type="xs:positiveInteger"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Databases" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Database" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
									<xs:attribute name="type" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:NMTOKEN">
												<xs:enumeration value="mysql"/>
												<xs:enumeration value="mysqli"/>
												<xs:enumeration value="pgsql"/>
												<xs:enumeration value="sqlite"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="name" type="xs:string" use="required"/>
									<xs:attribute name="label"/>
									<xs:attribute name="host" type="xs:string"/>
									<xs:attribute name="port" type="xs:unsignedInt"/>
									<xs:attribute name="user" type="xs:string"/>
									<xs:attribute name="password" type="xs:string"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== k1000nary/simulator/src/EUREKA/G6KBundle/Resources/data/databases/DataSources.xml
<?xml version="1.0" encoding="UTF-8"?>
<DataSources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../doc/DataSources.xsd">
	<DataSource id="1" type="internal" name="cout-certificat-immatriculation" database="1">
		<Description><![CDATA[Données de références pour le calcul du coût du cerficat d'immatriculation]]></Description>
		<Table id="1" name="baremeDemarche" label="Barème par nature de démarche">
			<Description><![CDATA[Barème applicable selon la nature de la démarche]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="demarche" type="text" label="Démarche">
				<Description><![CDATA[Libellé de la démarche]]></Description>
			</Column>
			<Column id="3" name="baremeMotoMoins125" type="number" label="Barème moto (2 ou 3 roues) de moins de 125cm3">
				<Description><![CDATA[Barème applicable à une moto (2 ou 3 roues) de moins de 125cm3 pour cette démarche]]></Description>
			</Column>
			<Column id="4" name="baremeAutre" type="number" label="Barème autre véhicule">
				<Description><![CDATA[Barème applicable aux autres types de véhicule pour cette démarche]]></Description>
			</Column>
		</Table>
		<Table id="2" name="baremeVehicule" label="Barème par type de véhicule">
			<Description><![CDATA[Barème applicable selon le type de véhicule]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="typeVehicule" type="text" label="Type de véhicule">
				<Description><![CDATA[Type de véhicule]]></Description>
			</Column>
			<Column id="3" name="baremeMoins10" type="number" label="Barème véhicule neuf ou moins de 10 ans">
				<Description><![CDATA[Barème applicable à un véhicule neuf ou de moins de 10 ans]]></Description>
			</Column>
			<Column id="4" name="baremePlus10" type="number" label="Barème véhicule de plus de 10 ans">
				<Description><![CDATA[Barème applicable à un véhicule de plus de 10 ans]]></Description>
			</Column>
			<Column id="5" name="taxeFPTransport" type="money" label="Taxe formation professionnelle dans les transports">
				<Description><![CDATA[Y2 - Taxe en euros sur la formation professionnelle dans les transports en fonction du PTAC]]></Description>
			</Column>
		</Table>
		<Table id="3" name="malusCV" label="Montants du malus selon la puissance fiscale">
			<Description><![CDATA[Montants du malus selon la puissance fiscale du véhicule et l'année d'achat]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="annee" type="year" label="Année d'achat du véhicule">
				<Description><![CDATA[Année d'achat du véhicule]]></Description>
			</Column>
			<Column id="3" name="minCV" type="integer" label="Borne inférieure du nombre de CV">
				<Description><![CDATA[Borne inférieure du nombre de CV fiscaux]]></Description>
			</Column>
			<Column id="4" name="maxCV" type="integer" label="Borne supérieure du nombre de CV">
				<Description><![CDATA[Borne supérieure du nombre de CV fiscaux]]></Description>
			</Column>
			<Column id="5" name="malus" type="money" label="Montant du malus">
				<Description><![CDATA[Montant du malus en euros]]></Description>
			</Column>
		</Table>
		<Table id="4" name="malusCO2" label="Montants du malus selon le taux d'émission de CO2 par kilomètre">
			<Description><![CDATA[Montants du malus en fonction du nombre de grammes de CO2 émis par kilomètre et l'année d'achat]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="annee" type="year" label="Année d'achat du véhicule">
				<Description><![CDATA[Année d'achat du véhicule]]></Description>
			</Column>
			<Column id="3" name="minCO2" type="integer" label="Borne inférieure du taux d'émission de CO2">
				<Description><![CDATA[Borne inférieure du nombre de grammes de CO2 émis par kilomètre]]></Description>
			</Column>
			<Column id="4" name="maxCO2" type="integer" label="Borne supérieure du taux d'émission de CO2">
				<Description><![CDATA[Borne supérieure du nombre de grammes de CO2 émis par kilomètre]]></Description>
			</Column>
			<Column id="5" name="malus" type="money" label="Montant du malus">
				<Description><![CDATA[Montant du malus en euros]]></Description>
			</Column>
		</Table>
		<Table id="5" name="taxeAdditionnelleCO2" label="Taxe additionnelle CO2">
			<Description><![CDATA[Taxe additionnelle CO2 en fonction du nombre de grammes de CO2 émis par kilomètre et l'année d'achat pour les véhicules ayant fait l'objet d'une réception communautaire]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="annee" type="year" label="Année d'achat du véhicule">
				<Description><![CDATA[Année d'achat du véhicule]]></Description>
			</Column>
			<Column id="3" name="tranche" type="integer" label="Tranche du barême taxe additionnelle CO2">
				<Description><![CDATA[Tranche du barême taxe additionnelle CO2]]></Description>
			</Column>
			<Column id="4" name="minCO2" type="integer" label="Borne inférieure du taux d'émission de CO2">
				<Description><![CDATA[Borne inférieure du nombre de grammes de CO2 émis par kilomètre]]></Description>
			</Column>
			<Column id="5" name="maxCO2" type="integer" label="Borne supérieure du taux d'émission de CO2">
				<Description><![CDATA[Borne supérieure du nombre de grammes de CO2 émis par kilomètre]]></Description>
			</Column>
			<Column id="6" name="taxeParGramme" type="money" label="Montant en euros de la taxe par gramme de CO2">
				<Description><![CDATA[Montant en euros de la taxe par gramme de CO2 émis par kilomètre]]></Description>
			</Column>
		</Table>
		<Table id="6" name="taxeAdditionnelleCV" label="Taxe additionnelle selon la puissance fiscale">
			<Description><![CDATA[Taxe additionnelle en fonction de la puissance fiscale et l'année d'achat pour les véhicules n'ayant pas fait l'objet d'une réception communautaire]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="annee" type="year" label="Année d'achat du véhicule">
				<Description><![CDATA[Année d'achat du véhicule]]></Description>
			</Column>
			<Column id="3" name="minCV" type="integer" label="Borne inférieure du nombre de CV">
				<Description><![CDATA[Borne inférieure du nombre de CV fiscaux]]></Description>
			</Column>
			<Column id="4" name="maxCV" type="integer" label="Borne supérieure du nombre de CV">
				<Description><![CDATA[Borne supérieure du nombre de CV fiscaux]]></Description>
			</Column>
			<Column id="5" name="taxe" type="money" label="Montant en euros de la taxe">
				<Description><![CDATA[Montant en euros de la taxe]]></Description>
			</Column>
		</Table>
		<Table id="7" name="taxeRegionale" label="Taxe régionale">
			<Description><![CDATA[Y1 - Taxe régionale pour 1 CV fiscal]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="regionId" type="choice" label="Région">
				<Description><![CDATA[Identifiant de la région dans la table des régions]]></Description>
				<Choices>
					<Source id="1" datasource="cout-certificat-immatriculation" request="select * from regions order by name" returnType="assocArray" valueColumn="codeRegion" labelColumn="name"></Source>
				</Choices>
			</Column>
			<Column id="3" name="taxe" type="money" label="Montant en euros de la taxe régionale">
				<Description><![CDATA[Montant en euros de la taxe pour 1 CV fiscal]]></Description>
			</Column>
			<Column id="4" name="exoVehiculePropre" type="percent" label="Pourcentage exonération véhicules propres">
				<Description><![CDATA[Pourcentage d’exonération de la taxe régionale pour les véhicules propres]]></Description>
			</Column>
		</Table>
		<Table id="8" name="regions" label="Régions">
			<Description><![CDATA[Régions]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="codeRegion" type="integer" label="Code région">
				<Description><![CDATA[Code de la région]]></Description>
			</Column>
			<Column id="3" name="name" type="text" label="Nom de la région">
				<Description><![CDATA[Nom de la région]]></Description>
			</Column>
		</Table>
		<Table id="9" name="departements" label="Départements">
			<Description><![CDATA[Départements]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
			<Column id="2" name="codeDep" type="department" label="Code du département">
				<Description><![CDATA[Code du département]]></Description>
			</Column>
			<Column id="3" name="name" type="text" label="Nom du département">
				<Description><![CDATA[Nom du département]]></Description>
			</Column>
			<Column id="4" name="regionId" type="choice" label="Région">
				<Description><![CDATA[Identifiant de la région d'appartenance dans la table des régions]]></Description>
				<Choices>
					<Source id="1" datasource="cout-certificat-immatriculation" request="select * from regions order by name" returnType="assocArray" valueColumn="codeRegion" labelColumn="name"></Source>
				</Choices>
			</Column>
		</Table>
		<Table id="10" name="energies" label="Catégories énergétiques">
			<Description><![CDATA[Catégories énergétiques]]></Description>
			<Column id="1" name="id" type="integer" label="id">
				<Description><![CDATA[Identifiant interne]]></Description>
			</Column>
